export const knowledgeBase = {
  general: {
    name: "Dr. Asif Ali",
    title: "MD, FACC, FHRS",
    profession: "Cardiologist & Digital Health Advisor",
    location: "Houston, Texas",
    specialties: ["Clinical Cardiology", "Cardiac Electrophysiology", "Digital Health Innovation"],
    education: [
      "Medical Degree from The University of Texas Medical Branch",
      "Internal Medicine Residency at Baylor College of Medicine",
      "Cardiology Fellowship at Texas Heart Institute",
      "Cardiac Electrophysiology Fellowship at Texas Heart Institute",
    ],
    certifications: [
      "Board Certified in Internal Medicine",
      "Board Certified in Cardiovascular Disease",
      "Board Certified in Clinical Cardiac Electrophysiology",
    ],
  },

  clinical: {
    role: "Director of Cardiac Electrophysiology",
    institution: "Houston Cardiovascular Center",
    expertise: [
      "Heart Rhythm Disorders",
      "Atrial Fibrillation",
      "Ventricular Tachycardia",
      "Cardiac Device Implantation",
      "Catheter Ablation",
      "POTS (Postural Orthostatic Tachycardia Syndrome)",
      "Dysautonomia",
      "Preventive Cardiology",
    ],
    procedures: [
      "Pacemaker Implantation",
      "Defibrillator Implantation",
      "Cardiac Resynchronization Therapy",
      "Catheter Ablation for Arrhythmias",
      "Leadless Pacemakers",
      "Subcutaneous ICDs",
      "Tilt Table Testing",
      "Autonomic Function Testing",
    ],
    conditions: [
      "POTS (Postural Orthostatic Tachycardia Syndrome)",
      "Dysautonomia",
      "Atrial Fibrillation",
      "Ventricular Tachycardia",
      "Heart Failure",
      "Coronary Artery Disease",
      "Post-COVID Cardiovascular Complications",
      "Hypertension",
      "Syncope",
      "Palpitations",
    ],
    treatments: {
      pots: [
        "Medication management (beta-blockers, fludrocortisone, midodrine, SSRIs)",
        "Exercise rehabilitation protocols",
        "Increased salt and fluid intake",
        "Compression garments",
        "Lifestyle modifications",
      ],
      arrhythmias: [
        "Antiarrhythmic medications",
        "Catheter ablation",
        "Device therapy (pacemakers, ICDs)",
        "Anticoagulation management",
      ],
      preventive: [
        "Risk factor modification",
        "Advanced lipid management",
        "Hypertension control",
        "Lifestyle interventions",
      ],
    },
    approach: "Patient-centered care combining clinical expertise with technological innovation",
  },

  research: {
    focus: [
      "Digital Health Technologies in Cardiology",
      "Remote Patient Monitoring",
      "AI Applications in Cardiac Care",
      "Wearable Cardiac Devices",
      "Predictive Analytics for Cardiac Events",
      "POTS and Dysautonomia",
      "Post-COVID Cardiovascular Effects",
      "Health Equity in Cardiovascular Care",
    ],
    publications: {
      count: "Over 50 peer-reviewed publications",
      highlights: [
        "Digital Biomarkers for Early Detection of Atrial Fibrillation",
        "Machine Learning Algorithms for Predicting Heart Failure Readmissions",
        "Wearable Technology for Continuous Cardiac Monitoring",
        "Remote Patient Monitoring in Post-Procedure Cardiac Care",
        "Circle of Vieussens: Its Importance in the Presence of Significant Coronary Artery Stenosis in a 26-Year-Old Female With Kawasaki Disease (Cureus, August 2024)",
        "Mal De Debarquement Syndrome: An Often Unrecognized and Unreported Condition (Cureus, July 2024)",
        "Brief Review and Primer of Key Terminology for Artificial Intelligence and Machine Learning in Hypertension (American Heart Association Journals – Hypertension, July 2024)",
        "Mental Health Applications of Generative AI and Large Language Modeling in the United States (MDPI-Digital Mental Health, July 2024)",
        "High Altitude, Air Travel, and Heart Disease (UpToDate, March 2023)",
      ],
    },
    clinicalTrials: [
      "Valencell: Fingertip and Wrist Blood Pressure Data Collection in Older Adults (2023)",
      "Enhanced External Counterpulsation Effects (2022-2023)",
      "Thrive360: Virtual Reality Cognitive Behavioral Therapy (2022-2023)",
      "TargetBP: Renal Denervation Study (2019-2022)",
    ],
    collaborations: [
      "Texas Heart Institute",
      "University of Texas Health Science Center",
      "PLX Health",
      "Cena Research Institute",
      "Major Medical Device Companies",
    ],
    institute: "Director of the Cena Research Institute (2023-Present)",
  },

  ventures: {
    currentRoles: [
      "Chief Medical Officer at Tabia Health (2024-Present) - AI-powered digital care pathway orchestration",
      "Managing Director US at FirstHX (2024-Present) - Knowledge-based history taking solution",
      "Chief Medical Officer at Healthseers/Cardio (2024-Present) - AI-enhanced PhonoCardioGraphy",
      "Chief Medical Advisor at Avive AED (2017-Present) - Next-generation Automated External Defibrillators",
      "Chief Consultant at Cena Ventures (2005-Present) - Advisory practice for healthcare technology companies",
    ],
    previousRoles: [
      "Global Chief Medical Officer at Qardio (2022-2024) - Remote Patient Monitoring and Remote Cardiac Rehabilitation",
      "Chief Medical Officer at Thrive360 (2021-2023) - Oculus-based Virtual Reality Mental Health Solution",
    ],
    advisor: [
      "JP Morgan Health",
      "Abbott Laboratories",
      "Fitbit Health Solutions",
      "EPAM Systems",
      "Avive Solutions",
      "CloudSteam Medical Imaging",
      "Lumi Health",
      "PLX Pharma",
      "Preventric",
      "Curogram",
      "Vsee",
      "Fruit Street",
    ],
    consultant: ["Digital Health Startups", "Medical Device Companies", "Healthcare Investment Firms"],
    entrepreneur: {
      description:
        "Founder of health technology ventures focused on improving cardiac care delivery and patient outcomes",
    },
    expertise: [
      "Digital Health Strategy",
      "Medical Device Development",
      "Healthcare Innovation",
      "Clinical Validation of Health Technologies",
      "Regulatory Pathways for Health Tech",
      "AI in Healthcare",
      "Remote Patient Monitoring",
      "Digital Therapeutics",
    ],
    companies: {
      tabia: "AI-powered digital care pathway orchestration platform",
      firsthx: "Knowledge-based history taking solution for patient communication",
      healthseers: "AI-enhanced PhonoCardioGraphy solution for heart defect detection",
      avive: "Manufacturer of next-generation Automated External Defibrillators",
      qardio: "Remote Patient Monitoring and Remote Cardiac Rehabilitation",
      thrive360: "Oculus-based Virtual Reality Mental Health Solution",
    },
  },

  speaking: {
    topics: [
      "The Future of Digital Cardiology",
      "AI and Machine Learning in Cardiac Care",
      "Remote Patient Monitoring Revolution",
      "Digital Transformation in Healthcare",
      "Physician Entrepreneurship in Health Tech",
      "POTS and Dysautonomia: Advances in Diagnosis and Treatment",
      "Post-COVID Cardiovascular Complications",
      "Health Equity in Cardiovascular Care",
    ],
    audiences: [
      "Medical Conferences",
      "Healthcare Innovation Summits",
      "Investment Forums",
      "Corporate Events",
      "Academic Institutions",
      "Patient Advocacy Groups",
    ],
    media: [
      "Fox News Medical Contributor",
      "Featured on Dr. Oz Show",
      "Healthcare Innovation Podcasts",
      "Medical Journal Interviews",
    ],
  },

  contact: {
    professional: "For professional inquiries, please use the contact form on this website",
    speaking: "For speaking engagements, please submit details through the speaking request form",
    media: "For media inquiries, please indicate the nature of your request in the contact form",
  },
}

// Keywords that help identify the intent of user questions
export const keywordCategories = {
  clinical: [
    "cardiology",
    "cardiologist",
    "heart",
    "cardiac",
    "electrophysiology",
    "electrophysiologist",
    "arrhythmia",
    "afib",
    "atrial fibrillation",
    "pacemaker",
    "defibrillator",
    "ablation",
    "heart rhythm",
    "patient",
    "treatment",
    "procedure",
    "medical",
    "doctor",
    "physician",
    "practice",
    "clinic",
    "hospital",
    "care",
    "health",
    "condition",
    "symptoms",
    "diagnosis",
    "therapy",
    "device",
    "implant",
    "surgery",
    "consultation",
    "appointment",
    "clinical",
    "pots",
    "dysautonomia",
    "postural orthostatic tachycardia syndrome",
    "treat",
    "treating",
    "treats",
    "approach",
    "manage",
    "manages",
    "managing",
    "heart failure",
    "coronary",
    "cardiovascular",
    "hypertension",
    "high blood pressure",
    "syncope",
    "fainting",
    "palpitations",
    "tilt table",
    "autonomic",
    "medication",
    "beta blocker",
    "fludrocortisone",
    "midodrine",
    "compression",
    "salt",
    "fluid",
    "exercise",
    "rehabilitation",
    "lifestyle",
    "houston cardiovascular",
    "preventive",
    "prevention",
    "post-covid",
    "long covid",
  ],

  research: [
    "research",
    "resaerch", // Common typo
    "reserch", // Another common typo
    "study",
    "studies",
    "publication",
    "paper",
    "journal",
    "article",
    "trial",
    "clinical trial",
    "investigation",
    "experiment",
    "data",
    "findings",
    "discovery",
    "innovation",
    "development",
    "technology",
    "science",
    "scientific",
    "academic",
    "publish",
    "published",
    "author",
    "authored",
    "collaborate",
    "collaboration",
    "contribution",
    "analysis",
    "methodology",
    "results",
    "conclusion",
    "hypothesis",
    "theory",
    "evidence",
    "cena research",
    "institute",
    "peer-reviewed",
    "digital biomarker",
    "machine learning",
    "artificial intelligence",
    "ai",
    "wearable",
    "remote monitoring",
    "predictive analytics",
    "health equity",
    "valencell",
    "counterpulsation",
    "renal denervation",
    "targetbp",
    "cureus",
    "american heart association",
    "hypertension journal",
    "mdpi",
    "uptodate",
  ],

  ventures: [
    "venture",
    "business",
    "company",
    "startup",
    "enterprise",
    "firm",
    "corporation",
    "industry",
    "commercial",
    "market",
    "product",
    "service",
    "solution",
    "advisor",
    "consultant",
    "executive",
    "founder",
    "entrepreneur",
    "investor",
    "investment",
    "partner",
    "collaboration",
    "strategic",
    "innovation",
    "development",
    "technology",
    "digital",
    "platform",
    "application",
    "software",
    "hardware",
    "device",
    "system",
    "companies",
    "work with",
    "advise",
    "consult",
    "board",
    "director",
    "leadership",
    "management",
    "corporate",
    "business",
    "commercial",
    "industry",
    "tabia",
    "qardio",
    "firsthx",
    "healthseers",
    "avive",
    "thrive360",
    "cena ventures",
    "jp morgan health",
    "abbott",
    "fitbit",
    "epam",
    "cloudsteam",
    "lumi health",
    "plx",
    "preventric",
    "curogram",
    "vsee",
    "fruit street",
    "cmo",
    "chief medical officer",
    "chief consultant",
    "chief advisor",
    "advisory",
    "digital health",
    "health tech",
    "medical device",
    "healthcare technology",
    "ai platform",
    "remote monitoring",
    "digital therapeutics",
    "virtual reality",
    "vr",
    "aed",
    "defibrillator",
    "phonocardiography",
  ],

  speaking: [
    "speak",
    "speaker",
    "speaking",
    "talk",
    "presentation",
    "lecture",
    "keynote",
    "address",
    "conference",
    "event",
    "summit",
    "symposium",
    "forum",
    "panel",
    "discussion",
    "webinar",
    "seminar",
    "workshop",
    "meeting",
    "convention",
    "audience",
    "attendee",
    "participant",
    "engagement",
    "appearance",
    "schedule",
    "booking",
    "fee",
    "topic",
    "subject",
    "content",
    "present",
    "presenter",
    "presenting",
    "speech",
    "talk",
    "speaker fee",
    "honorarium",
    "medical conference",
    "healthcare summit",
    "innovation forum",
    "corporate event",
    "academic lecture",
    "patient advocacy",
  ],

  media: [
    "media",
    "press",
    "news",
    "interview",
    "feature",
    "article",
    "story",
    "coverage",
    "publicity",
    "journalist",
    "reporter",
    "editor",
    "producer",
    "broadcast",
    "television",
    "TV",
    "radio",
    "podcast",
    "publication",
    "magazine",
    "newspaper",
    "online",
    "digital",
    "social media",
    "platform",
    "channel",
    "network",
    "program",
    "show",
    "segment",
    "appearance",
    "quote",
    "fox news",
    "dr oz",
    "dr. oz",
    "contributor",
    "medical expert",
    "healthcare expert",
    "commentary",
    "opinion",
    "editorial",
    "press release",
    "media kit",
    "spokesperson",
  ],

  contact: [
    "contact",
    "reach",
    "connect",
    "message",
    "inquiry",
    "question",
    "request",
    "information",
    "details",
    "email",
    "phone",
    "call",
    "text",
    "form",
    "submit",
    "send",
    "receive",
    "response",
    "reply",
    "answer",
    "availability",
    "schedule",
    "appointment",
    "meeting",
    "consultation",
    "get in touch",
    "reach out",
    "contact form",
    "contact info",
    "contact information",
    "contact details",
    "contact page",
    "email address",
    "phone number",
    "office contact",
    "assistant",
    "secretary",
    "staff",
  ],

  about: [
    "about",
    "bio",
    "biography",
    "background",
    "history",
    "profile",
    "information",
    "detail",
    "personal",
    "professional",
    "career",
    "experience",
    "expertise",
    "specialty",
    "qualification",
    "credential",
    "certification",
    "education",
    "training",
    "degree",
    "school",
    "university",
    "college",
    "graduate",
    "alumni",
    "achievement",
    "award",
    "recognition",
    "honor",
    "life",
    "about page",
    "about section",
    "who is",
    "background info",
    "professional background",
    "medical training",
    "medical education",
    "board certification",
    "fellowship",
    "residency",
    "medical school",
    "university of texas",
    "baylor",
    "texas heart institute",
  ],

  cv: [
    "cv",
    "curriculum vitae",
    "resume",
    "credentials",
    "qualifications",
    "experience",
    "history",
    "background",
    "education",
    "training",
    "certification",
    "skill",
    "expertise",
    "specialty",
    "achievement",
    "accomplishment",
    "publication",
    "presentation",
    "award",
    "honor",
    "recognition",
    "affiliation",
    "membership",
    "association",
    "society",
    "committee",
    "position",
    "role",
    "title",
    "professional history",
    "work history",
    "career summary",
    "professional summary",
    "academic record",
    "academic history",
    "professional record",
    "cv page",
    "download cv",
    "view cv",
  ],

  location: [
    "where",
    "located",
    "location",
    "based",
    "office",
    "practice location",
    "city",
    "state",
    "address",
    "region",
    "area",
    "place",
    "town",
    "country",
    "work from",
    "live",
    "reside",
    "residence",
    "hometown",
    "houston",
    "texas",
    "tx",
    "medical center",
    "texas medical center",
    "clinic location",
    "office address",
    "practice address",
    "directions",
    "map",
    "find",
    "visit",
  ],
}

// Function to identify the category of a question based on keywords
export function identifyQuestionCategory(question: string): string[] {
  const normalizedQuestion = question.toLowerCase()
  const categories: string[] = []

  // Check for pronouns that might refer to Dr. Ali
  const containsRelevantPronouns = /\b(he|his|him|doctor|dr|asif|ali)\b/i.test(normalizedQuestion)

  // Check each category for keyword matches
  for (const [category, keywords] of Object.entries(keywordCategories)) {
    for (const keyword of keywords) {
      if (normalizedQuestion.includes(keyword.toLowerCase())) {
        categories.push(category)
        break
      }
    }
  }

  // If the question contains pronouns but no specific category was identified,
  // it might be a general question about Dr. Ali
  if (containsRelevantPronouns && categories.length === 0) {
    categories.push("general")
  }

  // If no category was identified, mark as unknown
  if (categories.length === 0) {
    categories.push("unknown")
  }

  return categories
}

// Function to extract relevant information from the knowledge base based on the question category
export function getRelevantInformation(categories: string[]): any {
  const information: any = {}

  for (const category of categories) {
    if (category !== "unknown" && knowledgeBase[category as keyof typeof knowledgeBase]) {
      information[category] = knowledgeBase[category as keyof typeof knowledgeBase]
    }
  }

  return information
}
